// highlight http request (and json body if applicable) then type ctrl + alt + R

///
////
///// projects
////
///

//
// local
//
GET http://localhost:8080/projects

###
GET http://localhost:8080/projects/681fee16bf7e8fcb85af409a

###
POST http://localhost:8080/projects HTTP/1.1
content-type: application/json

{
    "name":"cool app",
    "startDate":"Feb",
    "endDate":"Mar",
    "url":"youtube.com",
    "type":"personal",
    "details":"I made this ... blah blah",
    "stack":"Javascript, Nodejs, Render, Mongodb"
}

###
PUT http://localhost:8080/projects/681fee16bf7e8fcb85af409a HTTP/1.1
content-type: application/json

{
    "name":"even cooler app",
    "startDate":"dec 2024",
    "endDate":"july 2025",
    "url":"github.com",
    "type":"school",
    "details":"Assignment blah blah",
    "stack":"React, Typescript, MUI, Postgres"
}

###
PUT http://localhost:8080/projects/681fee16bf7e8fcb85af409a HTTP/1.1
content-type: application/json

{
    "name":"coolest app"
}

###
DELETE http://localhost:8080/projects/681ffcbc6332ce3fe196a4f4 HTTP/1.1

//
// production
//

###
GET https://experiences-api-cdf5.onrender.com/projects

###
GET https://experiences-api-cdf5.onrender.com/projects/6816c31651de9aab35415445


###
POST https://experiences-api-cdf5.onrender.com/projects HTTP/1.1
content-type: application/json

{
    "name":"cool app",
    "startDate":"Feb",
    "endDate":"Mar",
    "url":"youtube.com",
    "type":"personal",
    "details":"I made this ... blah blah",
    "stack":"Javascript, Nodejs, Render, Mongodb"
}

###
PUT https://experiences-api-cdf5.onrender.com/projects/681ffd396332ce3fe196a4f6 HTTP/1.1
content-type: application/json

{
    "name":"even cooler app",
    "startDate":"dec 2024",
    "endDate":"july 2025",
    "url":"github.com",
    "type":"school",
    "details":"Assignment blah blah",
    "stack":"React, Typescript, MUI, Postgres"
}

###
PUT https://experiences-api-cdf5.onrender.com/projects/6816c36451de9aab35415447 HTTP/1.1
content-type: application/json

{
    "name":"Pan"
}

###
DELETE https://experiences-api-cdf5.onrender.com/projects/681fec87903dd5d23ce5ca65 HTTP/1.1

// highlight http request (and json body if applicable) then type ctrl + alt + R

///
////
///// jobs
////
///

//
// local
//
###
GET http://localhost:8080/jobs

###
GET http://localhost:8080/jobs/681fee16bf7e8fcb85af409a

###
POST http://localhost:8080/jobs HTTP/1.1
content-type: application/json

{
    "title":"good employee",
    "startDate":"Jan",
    "endDate":"April",
    "company":"BYUI",
    "details":"I made thiah blah"
}

###
PUT http://localhost:8080/jobs/681fee16bf7e8fcb85af409a HTTP/1.1
content-type: application/json

{
    "title":"top worker",
    "startDate":"dec 2020",
    "endDate":"july 2025",
    "company":"Church",
    "details":"blah",
}

###
PUT http://localhost:8080/jobs/681fee16bf7e8fcb85af409a HTTP/1.1
content-type: application/json

{
    "name":"the best employee"
}

###
DELETE http://localhost:8080/jobs/681ffcbc6332ce3fe196a4f4 HTTP/1.1

//
// production
//

###
GET https://experiences-api-cdf5.onrender.com/jobs

###
GET https://experiences-api-cdf5.onrender.com/jobs/6816c31651de9aab35415445

###
POST https://experiences-api-cdf5.onrender.com/jobs HTTP/1.1
content-type: application/json

{
    "title":"good employee",
    "startDate":"Jan",
    "endDate":"April",
    "company":"BYUI",
    "details":"I made thiah blah"
}

###
PUT https://experiences-api-cdf5.onrender.com/jobs/681ffd396332ce3fe196a4f6 HTTP/1.1
content-type: application/json

{
    "title":"top worker",
    "startDate":"dec 2020",
    "endDate":"july 2025",
    "company":"Church",
    "details":"blah",
}

###
PUT https://experiences-api-cdf5.onrender.com/jobs/6816c36451de9aab35415447 HTTP/1.1
content-type: application/json

{
    "name":"the best employee"
}

###
DELETE https://experiences-api-cdf5.onrender.com/jobs/681fec87903dd5d23ce5ca65 HTTP/1.1

///
////
///// certifications
////
///

//
// local
//
###
GET http://localhost:8080/certifications

###
GET http://localhost:8080/certifications/681fee16bf7e8fcb85af409a

###
POST http://localhost:8080/certifications HTTP/1.1
content-type: application/json

{
    "name":"cool certificaiton",
    "issueDate":"2023-05-01",
    "expireDate":"2025-05-01",
    "verificationUrl":"certified.com",
    "details":"I made thiah blah"
}

###
PUT http://localhost:8080/certifications/681fee16bf7e8fcb85af409a HTTP/1.1
content-type: application/json

{
    "name":"awesome certificaiton",
    "issueDate":"2020-05-01",
    "expireDate":"2025-05-01",
    "verificationUrl":"example.com",
    "details":"I made thiah blah"
}

###
PUT http://localhost:8080/certifications/681fee16bf7e8fcb85af409a HTTP/1.1
content-type: application/json

{
    "name":"the best cert"
}

###
DELETE http://localhost:8080/certifications/681ffcbc6332ce3fe196a4f4 HTTP/1.1

//
// production
//
###
GET https://experiences-api-cdf5.onrender.com/certifications

###
GET https://experiences-api-cdf5.onrender.com/certifications/681fee16bf7e8fcb85af409a

###
POST https://experiences-api-cdf5.onrender.com/certifications HTTP/1.1
content-type: application/json

{
    "name":"cool certificaiton",
    "issueDate":"2023-05-01",
    "expireDate":"2025-05-01",
    "verificationUrl":"certified.com",
    "details":"I made thiah blah"
}

###
PUT https://experiences-api-cdf5.onrender.com/certifications/681fee16bf7e8fcb85af409a HTTP/1.1
content-type: application/json

{
    "name":"awesome certificaiton",
    "issueDate":"2020-05-01",
    "expireDate":"2025-05-01",
    "verificationUrl":"example.com",
    "details":"I made thiah blah"
}

###
PUT https://experiences-api-cdf5.onrender.com/certifications/681fee16bf7e8fcb85af409a HTTP/1.1
content-type: application/json

{
    "name":"the best cert"
}

###
DELETE https://experiences-api-cdf5.onrender.com/certifications/681ffcbc6332ce3fe196a4f4 HTTP/1.1

///
////
///// organizations
////
///

//
// local
//
###
GET http://localhost:8080/organizations

###
GET http://localhost:8080/organizations/681fee16bf7e8fcb85af409a

###
POST http://localhost:8080/organizations HTTP/1.1
content-type: application/json

{
    "name": "any",
    "joinDate": "2023-05-01",
    "leaveDate": "2024-05-01",
    "type": "any",
    "details": "10 characters minimum",
}

###
PUT http://localhost:8080/organizations/681fee16bf7e8fcb85af409a HTTP/1.1
content-type: application/json

{
    "name": "asdfasfdsa",
    "joinDate": "2000-05-01",
    "leaveDate": "2024-05-01",
    "type": "aasfdsafdsa",
    "details": "10 characters minimum",
}

###
PUT http://localhost:8080/organizations/681fee16bf7e8fcb85af409a HTTP/1.1
content-type: application/json

{
    "name":"the best organization"
}

###
DELETE http://localhost:8080/organizations/681ffcbc6332ce3fe196a4f4 HTTP/1.1

//
// porduction
//
###
GET https://experiences-api-cdf5.onrender.com/organizations

###
GET https://experiences-api-cdf5.onrender.com/681fee16bf7e8fcb85af409a

###
POST https://experiences-api-cdf5.onrender.com/organizations HTTP/1.1
content-type: application/json

{
    "name": "any",
    "joinDate": "2023-05-01",
    "leaveDate": "2024-05-01",
    "type": "any",
    "details": "10 characters minimum",
}

###
PUT https://experiences-api-cdf5.onrender.com/organizations/681fee16bf7e8fcb85af409a HTTP/1.1
content-type: application/json

{
    "name": "asdfasfdsa",
    "joinDate": "2000-05-01",
    "leaveDate": "2024-05-01",
    "type": "aasfdsafdsa",
    "details": "10 characters minimum",
}

###
PUT https://experiences-api-cdf5.onrender.com/organizations/681fee16bf7e8fcb85af409a HTTP/1.1
content-type: application/json

{
    "name":"the best organization"
}

###
DELETE https://experiences-api-cdf5.onrender.com/organizations/681ffcbc6332ce3fe196a4f4 HTTP/1.1